[package]
name = "example_crate_with_settings"
version = "0.0.7"
edition = "2021"
authors = ["sam0x17"]
description = "A crate demonstrating configurable crate settings from the `crate-settings` crate"
license = "MIT"

[dependencies]
crate-settings = { path = "../../", version = "0" }
