[package]
name = "crate-settings"
version = "0.1.0"
edition = "2021"
authors = ["sam0x17"]
homepage = "https://sam0x17.dev"
description = "Set custom crate settings via a `[package.metadata.settings]` table in `Cargo.toml` and access these settings at compile-time and run-time."
keywords = ["settings", "compile-time", "environment", "feature"]
license = "MIT"

# the following metadata is used by tests
[package.metadata.settings]
example-crate = { some-key = "hey", something_else = false }
another-crate = { number = 33, float = 55.6, arr = ["a", "b", "c"] }

[dependencies]
