[package]
name = "workspace_root"
version = "0.0.4"
edition = "2021"
publish = false

[dependencies]
crate-settings = { path = "../../", version = "0.0.4" }

[package.metadata.settings]
inner_c = { only_outer = true, some_int = 67 }
