[package]
name = "inner_b"
version = "0.0.4"
edition = "2021"
publish = false

[dependencies]
crate-settings = { path = "../../../../", version = "0.0.4" }


[package.metadata.settings]
inner_c = { some_bool = true, some_int = 37 }
