[package]
name = "inner_a"
version = "0.0.5"
edition = "2021"
publish = false

[dependencies]
crate-settings = { path = "../../../", version = "0.0.5" }

[package.metadata.settings]
inner_c = { something_further_out = 44, some_int = 38 }
